services:

  postgres:
    image: postgres:16
    container_name: social_media_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: social_media_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: social_media_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka
    volumes:
      - ./backend/uploads:/app/uploads

  api-gateway:
    build: ./api-gateway
    container_name: social_media_api_gateway
    ports:
      - "8081:8081"
    depends_on:
      - backend
      - auth-service
      - discovery-server
    environment:
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka

  frontend:
    build: ./frontend
    container_name: social_media_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway

  nginx:
    build: ./nginx
    container_name: social_media_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api-gateway

  prometheus:
    image: prom/prometheus
    container_name: social_media_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: social_media_grafana
    ports:
      - "3000:3000"

  discovery-server:
    build: ./discovery-server
    container_name: social_media_discovery_server
    ports:
      - "8761:8761"

  auth-service:
    build: ./auth-service
    container_name: social_media_auth_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka

volumes:
  postgres_data: