server:
  port: 8080

spring:
  application:
    name: social-media-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/social_media_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: INFO

jwt:
  secret: 6a6f686e646f65736f6369616c6d6564696173797374656d7365637265746b657931323334353637383930
  expiration: 86400000